name: PuzzleBot
main: com.xuxe.puzzleBot.main.PuzzleBot
version: 1.0.0
author: ThatXuxe
commands:
  submit:
    permission: puzzlebot.submit
    permission-message: You do not have have permission to submit answers.
    aliases: answer
    usage: "Usage: /submit <submission>"
  puzzle:
    permission: puzzlebot.admin
    permission-message: You do not have the permission to use this command
    usage: "/puzzle reload"
permissions:
  puzzlebot.submit:
    description: Allows submit command
    default: true
  puzzlebot.admin:
    description: Allows administrator commands
    default: false